
import localFont from "next/font/local";

import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import { ThemeProvider } from "../components/theme-provider"
// import TopLoadingBar from "@/components/TopLoadingBar";
import TopLoadingBar from '../components/TopLoadingBar'

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Zain Bloger",
  description: "Generated by create next app",
};
//88:10:8f:7d:ef:40	
//192.168.1.3
//34:79:16:7b:20:40	
//192.168.1.2	  
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <TopLoadingBar />
        <ThemeProvider>
            <Navbar />
            {children}
            <Footer />
        </ThemeProvider>
      </body>

    </html>
  );
}
